### ISSUE TITLE
I made an account for this - Child Labor

### ISSUE THREAD

**Issue by Non-C** [twohoursonelife/junior#1]
- [x] !spawn - **Spawning works like this:** (2HOL GUIDE)

**USED A SEED;** you will spawn as an eve wherever that seed dropped you.  You can have babies there.
**DID NOT USE A SEED;** THERE IS A FERTILE FEMALE SOMEWHERE IN THE WORLD: you will spawn as a baby at the fertile female's feet.  Once you grow up and are female, you can have your own babies there.
**DID NOT USE A SEED;** THERE ARE NO FERTILE FEMALES AVAILABLE: you will spawn as an eve in the center of the map.  There is a stone with "unless" written on it, to mark the center.  The area to the east is called Public Town (PT).  You can have babies there.

- [x] !cool - **How to be cool on the 2HOL discord:** (2HOL guide)

1. Join and immediately say “Wow this game is dead.”
2. Ignore literally the 3 years of hard work from the devs only focus on the fact that no one has sent a discord message in 2 hours and there’s 5 people online.
3. Don’t listen to the people defending the game and call them toxic.
4. Accept help from no one in this game that revolves around people working together.
5. Call the game a shameless rip off of OHOL, disregarding the dev team’s work, and despite the fact that you can play for free.
6. Leave the server in anger at the ‘toxic community’

- [x] !fertile - **Fertility:** (2HOL GUIDE)

**MALE:** Never fertile.  Can’t have babies.
**FEMALE:** AGE 0-13: Too young.  Can’t have babies.
**FEMALE:** AGE 14-104: Fertile.  Can have babies.
**FEMALE:** AGE 105-120: Too old.  Can’t have babies.

When you are fertile, you can manually turn off your fertility at any time by saying “no bb” or something similar.  When you are infertile inside your fertile years, you can turn on your fertility at any time by saying “gimme bb” or something similar.  In the vanilla client you will hear a ‘ding’ sound if you have said a correct phrase.  This is not the case for modded clients, however.  Sidenote, the ability to breastfeed is tied to natural fertility.  Only women between 14-104 can breastfeed children by picking them up.  Fertility commands don't effect ability to breastfeed.

- [x] !spawnas - **How do you want to spawn next life?** (2HOL GUIDE)

**Be born as a baby:** Make sure you have no seed input, and simply click login.  You will spawn as the son or daughter to any woman on the server.  This is the only guaranteed way to see other players as you play, because you will at least have a mom, but likely an entire family around you.
**Spawn to a specific woman:** Repeat the same steps as being born to a random woman, and use the command /die to kill yourself and be blocked from spawning to the same woman until you find the one you’re looking for.
**Spawn as eve and start your own family:** Input any characters as a seed, and then click login.  You will spawn as a 14 year old girl usually in wilderness.  There is always a chance that a seed might drop you near someone else’s town, so if you want the full starting from scratch experience, you might have to try multiple times.  A list of public seeds of various levels of tech can be found on the wiki here: https://twohoursonelife.fandom.com/wiki/Spawn_seeds.  You are never guaranteed to see other players when using a seed.  You will spawn alone, and only have a chance of having babies, if other players follow options 1 or 2.

- [x] !cookie - How To Bake Cookies: (2HOL GUIDE)

**STEP 1:** Make flour.  This is done by using a sharp stone or flint chip on some ripe wheat.  Then, use a straight or small curves branch on the wheat sheaf that drops, in order to get some threshed wheat.  Pick that threshed wheat up in a bowl, and grind it with a round stone to make flour.
**STEP 2:** Make cream.  Shuck a corn cob and wait for it to dry.  Once it dries, put it in a bowl and grind it with a flint chip to become corn kernels.  Feed this bowl of kernels to a cow and wait with a bucket.  The cow will have a baby.  Once the baby goes free, the cow will be able to be milked.  Milk the cow and let the whole milk sit for 2 minutes to separate.  Once separated, skim the milk with a bowl to get a bowl of cream.
**STEP 3:** Make raw sugar.  Use a sharp stone or flint chip to harvest some sugarcane.  Then, use an axe to chop a singular cane of sugar into chunks.  Put the chunks in a bowl and grind them with a round stone.  Add water to the sugarcane pulp, and then boil it over hot coals.  After 10 seconds, you can take the cooked pulp off of the coals and cane juice into another bowl.  Boil the cane juice to make a bowl of raw sugar.
**STEP 4:** Make sugared cream.  Combine the cream with the raw sugar to make sugared cream.
**STEP 5:** Make cookie dough.  Combine the flour with the sugared cream to get a bowl of cookie dough.
**STEP 6:** Prepare the raw cookie(s).  Put the cookie dough on a flat rock and smash it with a long shaft.  Then, add a gooseberry to the cookie.  Use a plate on the flat rock to transfer the raw cookie onto the plate.  You can repeat this process and stack up to 4 cookies on 1 plate.
**STEP 7:** Cook the cookie(s).  Fire up an adobe oven by lighting some kindling and waiting for it to go out.  Cook the cookie(s) on the hot oven.
**STEP 8:** Enjoy your extra yum food with your family!

- [x] !wipe / !wipes - **WIPES:** (2HOL Guide)

A wipe is the deletion of the current world and everything built in it, and a regeneration of it all.  To emphasize, because the world is all one server, even something you have built at a private seed, will be deleted.  The entire world is regenerated as simple nature.  THIS IS NOT DONE OFTEN, DON'T WORRY!

Wipes happen about every 2/3 of a year, but are not on a schedule.  The devs decide when a wipe happens.  In order to minimize the amount of wipes done on the server, the devs try to attach lots of world changing content to each wipe, so there is enough interesting content to last between them.  World changing content is anything that changes the generation of the world, such as new animals, new biomes, new plants, etc.  This type of content requires a wipe to be added.  After a wipe, content focus is more shifted on craftable items, which don't require a wipe, as long as everything needed to make them is generated in the world already.

- [x] !seed / !makeseed - **How To Make A Seed:** (2HOL Guide)

There are 2 ways to make and use a seed 2HOL.

The first is to click on **[SETTINGS]**.
Then, find the box at the very bottom entitled **SPAWN SEED**.
If you’ve ever played Minecraft, seeds work similar to it, in that you can input any random characters and any amount of characters.
After you are happy with your seed, (your 5 most recent seeds will be saved after you use them once) click **[BACK]**.
Then, simply click **[LOGIN]** to use your seed.

The second option is to click on your **USERNAME** box.
Click after your username inside the box, and add a “|”.  Make sure not to add any spaces, and not to delete any part of your username.
If you’ve ever played Minecraft, seeds work similar to it, in that you can input any random characters and any amount of characters.  Put them after the |.
Then, simply click **[LOGIN]** to use your seed.

- [x] !emoticon - **How To Stop Discord From Automatically Changing Your Emoticons Into Emojis:**

1. You must be on PC to change this setting.
2. Go to user settings (the gear in the bottom left).
3. Find the 'Text & Images' tab.
4. Deselect the setting 'Automatically convert emoticons in your messages to emoji'.

:)

- [x] !rng - Generates a random number between 1-100

- [x] !flipcoin - Heads or Tails

- [x] !dye - "I like red!" "Green is the best!" "Blue would be nice!" "What about black!" "I think you look good in white!" "How about yellow!"

- [ ] !buildfloor - Says a random floor material.

- [ ] !buildwall - Says a random wall material.

- [ ] !yfg - (Yum Food Generator).  Says a random food.

- [x] !townidea - "Every town needs a bakery!" "Do you have a warm nursery with clothes for bbs?" "A fireplace room is a lovely addition to a house!" "A tavern with a distillery out back would be perfect for storing your beer and wine!" "Try and capture an animal from far away and make a petting zoo! (safety from bites not guaranteed)" "I love the look of blacksmith shops!" "How about a sewing room, or a tailor building?" "An airport so you can accept visitors from far away!" "Fishing huts and docks look wonderful on a lake or sea!" "Fruit orchards are so pretty!" "A hospital full of medical supplies would be useful!" etc.

- [x] !sus - "Rainie is sus, but I think liger bit someone..."

- [ ] !griefer - "smh dumb griefers"

- [x] !brickhead - "Dragon is the brick lord!"

- [x] !monolith - "Those monoliths in the desert look a little weird... They speak to me as a fellow magic machine.  They crave gold.  They say they might give you a relic from long ago."

- [x] !directory - "Dad likes to keep his guide library available for anyone to read! https://discord.gg/pb94MbTeFN"

**Comment by connorhsm** [comment]
Thank you!
As I add each one I'll tick them off in your comment. I've also made edits for formatting and clarity which I will edit into this comment as I go.
- Spawn: 'What happens when you spawn into the world?\n\n**Using a seed:** You will spawn as an eve wherever that seed dropped you. You can have babies there.\n**Without a seed:** If there **is** a fertile female in the world, you will spawn as a baby at their feet. If there **is not** a fertile female in the world, you will spawn as an Eve in the center of the map. There is a stone with "unless" written on it, to mark the center. The area to the east is called Public Town (PT).'
- Cool: 'How to be cool on the 2HOL Discord\n\n**1.** Join and immediately say “Wow this game is dead.”\n**2.** Ignore literally the 3 years of hard work from the devs only to focus on the fact that no one has sent a discord message in 2 hours and there\'s 5 people in game.\n**3.** Don\'t listen to the people defending the game and call them toxic.\n**4.** Accept help from no one in this game that revolves around people working together.\n**5.** Call the game a shameless rip off of OHOL, disregarding the premise of open source.\n**6.** Leave the server in anger at the \'toxic community\'.'
- Fertile: 'Fertility:\n\n**Male:** Never fertile, can\'t have babies.\n**Female, Age 0-13:** Too young, can\'t have babies.\n**Female, Age 14-104:** Fertile, can have babies.\n**Female, Age 105-120:** Too old, can\'t have babies.\n\nWhen you are fertile, you can manually turn off your fertility by saying "no bb". You can turn your fertility back on by saying "gimme bb". In the vanilla client you will hear a \'ding\' sound if you said the phrase correctly. Sidenote, fertility commands don\'t effect ability to breastfeed.'
- Spawnas: 'Different ways to spawn into the game:\n\n**Be born as a baby:** Make sure you have no seed input and simply click login. You will spawn as the son or daughter to any fertile woman on the server. This is the only guaranteed way to see other players as you play, because you will at least have a mother, but likely an entire family around you.\n**Spawn to a specific woman:** Repeat the same steps as being born to a random woman and use the command /die to kill yourself and be blocked from spawning to the same woman until you find the one you\'re looking for.\n**Spawn as Eve and start your own family:** Input any characters as a seed and then click login. You will spawn as a 14 year old girl usually in wilderness. There is always a chance that a seed might drop you near someone else\'s town, so if you want the full starting from scratch experience, you might have to try multiple times.\n\nA list of public seeds of various levels of tech can be found on the wiki here: https://twohoursonelife.fandom.com/wiki/Spawn_seeds. You are never guaranteed to see other players when using a seed. You will spawn alone and only have a chance of having babies if other players follow options 1 or 2.'
- Cookie: '**STEP 1:** Make flour. This is done by using a sharp stone or flint chip on some ripe wheat. Then use a straight or small curved branch on the wheat sheaf in order to get some threshed wheat. Pick that threshed wheat up in a bowl and grind it with a round stone to make flour.\n**STEP 2:** Make cream. Shuck a corn cob and wait for it to dry. Once it dries, put it in a bowl and grind it with a flint chip to become corn kernels. Feed this bowl of kernels to a cow and wait with a bucket. The cow will have a baby. Once the baby goes free the cow will be able to be milked. Milk the cow and let the whole milk sit for 2 minutes to separate. Once separated, skim the milk with a bowl to get a bowl of cream.\n**STEP 3:** Make raw sugar. Use a sharp stone or flint chip to harvest some sugarcane. Then use an axe to chop a singular cane of sugar into chunks. Put the chunks in a bowl and grind them with a round stone. Add water to the sugarcane pulp and then boil it over hot coals. After 10 seconds you can take the cooked pulp off of the coals and cane juice into another bowl. Boil the cane juice to make a bowl of raw sugar.\n**STEP 4:** Make sugared cream. Combine the cream with the raw sugar to make sugared cream.\n**STEP 5:** Make cookie dough. Combine the flour with the sugared cream to get a bowl of cookie dough.\n**STEP 6:** Prepare the raw cookies. Put the cookie dough on a flat rock and smash it with a long shaft. Then add a gooseberry to the cookie. Use a plate on the flat rock to transfer the raw cookie onto the plate. You can repeat this process and stack up to 4 cookies on 1 plate.\n**STEP 7:** Cook the cookies. Fire up an adobe oven by lighting some kindling and waiting for it to go out. Cook the cookies on the hot oven.\n**STEP 8:** Enjoy your extra yum food with your family!'
- Wipe: 'A map wipe is the deletion of the current world and everything built in it, this includes even your private seed as this is also a part of the world but usually just far far away. **Don\'t worry, this is not done often.**\n\nMape wipes are necessary so that certain new content can be added to the game. Any naturally generated feature such as a biome or plant will only appear after a wipe. A map wipe happens about two or three times a year, but there is no fixed schedule and it is up to the devs to decide when one is necessary.'
- Seed: 'A seed is a case sensitive "password" (and can include numbers and symbols) which will generate coordinates on the map as a location for you (or anyone else) to spawn. The same phrase will always spawn you at the same coordinates until the map is wiped. You should make your seed difficult to guess and keep it a secret if you do not want others to find you. Remeber that you are still in the same world as everyone else though and other players may happen to accidentally stumble into your area.\n\nThere are two ways to make a seed:\n**For the official 2HOL client,** from the main menu, click settings. Enter your desired seed into the box at the bottom titled \'Spawn Seed\', your 5 most recent seeds will also be saved for you. You can now go back to the main menu and login to spawn at the seed location.\n**For any other client such as Hetuw (also works for the official client),** on the main, click into the username field. At the end of your username type in the pipe character "|" (under the backspace key, using shift). Do not add any spaces. Enter your desired seed after the pipe character and login to spawn at the seed location.'
- Emoticon: '1. You must be on PC to change this setting.\n2. Go to user settings (the gear in the bottom left)\n3. Find the \'Text & Images\' tab\n4. Deselect the setting \'Automatically convert emoticons in your messages to emoji\'\n\n\:\)'

**Comment by connorhsm** [comment]
I have completed adding all commands that are ticked and have chosen not to add the griefer command :p
If you can get a list of responses for the remaining commands I'd be happy to add them.

**Comment by Non-C** [comment]
ahhhh Thank you so much!  Junior is amazing!  I never thought my silly suggestion could be turned into such a fun and useful tool xD Great work!!!

Here are the remaining commands!  As fun as it would be to grab some stakes ingame and try to find every wall that can be built on them, I decided not to finish that list...  That idea can be scrapped!  I'll also add the twinning guide I made since Junior was created.  Also, like the monolith command, I thought it would be kinda fun if Junior gave hints about some of the magical items ingame, so I wrote a few responses to those.  You can add them if you want but it's no big deal.



/yfg - Gooseberry, Wild Carrot, Cooked Rabbit, Gooseberry Bowl, Berry Pie, Carrot Pie, Rabbit Pie, Berry Carrot Pie, Berry Rabbit Pie, Rabbit Carrot Pie, Berry Carrot Rabbit Pie, Domestic Carrot, Cooked Goose, Cooked Mutton, Cactus Fruit, Mutton Pie, Burdock, Wild Onion, Shroom, Corn, Popcorn, Baked Potato, Green Bean Bowl, Sauerkraut, 3 Sisters Stew, Omelette, Baked Beans, Bean Burrito. Bean Taco, Carnitas, Pork Taco, Bowl of Whole Milk, Pouch of Whole Milk, Bottle of Whole Milk, Buttered Bread, Bread, Bowl of Skim Milk, Pouch of Skim Milk, Bottle of Skim Milk, Mango, Mango Slice, Banana, Turkey Slice, Turkey Drumstick, Bowl of Turkey Broth, Pouch of Turkey Broth, Bottle of Turkey Broth, Ice Cream, Wild Pepper, Shrimp, Tomato, Hot Pepper, Onion, Tortilla Chip, Salsa, French Fry, Ketchup, Pumpkin Pie, Flatbread, Cheese Sandwich, Mutton Sandwich, Cheese, Beer, Bee Comb, Honey, Apple, Sunny Egg, Apple Pie, Baked Chicken, Char, Sausage, Bacon, Cooked Pork, Lobster, Crab, Boiled Egg, Steak Pie, Steak and Onion Pie, Pork Pie, Honey Bunny Pie, Pork and Apple Pie, Chicken Pie, Grapes, Wine, Orange, Lemon, Split Coconut, Drilled Coconut, Cooked Beef, Cod, Bass, Pike, Trout, Sardines, Cookie, Roast Pig Dinner, Chilli Con Carne, Pancakes, Rice, Tomato Soup, Shroom Soup, French Onion Soup


/about - Hello!  I am Non-C Junior, your friendly neighborhood guide-spam bot!  Created by Colin to save my other dad some time as he works as the human version of that idea that a monkey hitting keys for long enough will eventually result in something useful, I have many features, including posting Non-C's guides, insight on some of the mysterious things you might find in the wonderful 2HOL world, trying my best to make this place fun, and more!

All of the guides that I post come from Non-C's Guide Directory.  If you're interested in joining the official Discord server for them, use the command !directory.  You can look through guides, see their commands to let me know to post them in the 2HOL server, and suggest new ones be written!

I hope to see you around!  Junior slep now!


/twin - How To Twin (Play With Friends) (2HOL guide)

Twinning is the broad term used for spawning with up to 3 friends at the same location at the same time.  It is the most convenient way to play with friends.

To twin, press the [FRIENDS] button.  Then, you will see a twin code at the top of the screen.  Randomly generated twin codes are 3 random words.  You can put whatever you want as your twin code, as long as it matches what your friend(s) puts in.  After you have your twin code written, press the button at the bottom for how many players will be using the code.
Twins = 2 people
Triplets = 3 people
Quadruplets = 4 people
After you have pressed the button, hit [LOGIN]  The screen will say "Waiting to be born as twins/triplets/quadruplets." until the last person hits [LOGIN]

If any of the group has a seed in either seed box, the twins will spawn as eves there.  Sadly the eves aren't related, but will all have the same model.  You can all choose different last names.  If multiple people have seeds, the last person with one to hit [LOGIN] will decide where the game places you.  If you do not want to spawn as eves, make sure that everyone in the group has removed their seeds.  Then, you will spawn as babies to the same mother at the same time.  You will be identical twins and all have the same model.



/wildcarrot - Wild carrots have something of a magical property to them.  Aside from shapeshifting slightly when taken out of a bowl, they like to sleep at shrines to the dead.  They have told me that if you allow them to rest undisturbed for a lifetime, that they will thank you with riches.

...Oh, you want to know more?  How am I supposed to talk to them?  They're just a plant, silly.



/magicfeather - Magic feathers are one of few relics that remain of the long-forgotten times.  They are also some of the most powerful.  They can tear down ancient walls, grow a fruit tree, long extinct, and... um... turn into a helicopter.  Look, don't question it.  Those times were weird.  Because of their power, they can't be trusted with just anyone.  Only the devs and mods can create them.  If you need something like an ancient wall removed, ask in general!

**Comment by Non-C** [comment]
Updated Guides:
/seed - What are Seeds in 2HOL?

A seed is a case sensitive "password" (and can include numbers and symbols) which will generate coordinates on the map as a location for you (or anyone else) to spawn. The same phrase will always spawn you at the same coordinates until the map is wiped. You should make your seed difficult to guess and keep it a secret if you do not want others to find you. Remeber that you are still in the same world as everyone else though and other players may happen to accidentally stumble into your area.

There are two ways to make a seed:
**For the official 2HOL client,** from the title screen, click the rectangle that says **”SPAWN SEED”**.  Type in your decided seed.  Previous seeds that you have used will appear above the rectangle for you to click on, as well.  Then, simply click the **[SEED]** button to spawn with that seed.  (Clicking **[BE BORN]** on the title screen will always ignore the seed inputted.  If you are twinning, however, clicking the **[BE BORN]** in the bottom right corner of the **[FRIENDS]** tab WILL take your seed into account.  Remember to remove it if you want to spawn as twin as babies.
**For any other client such as Hetuw,** on the main, click into the username field. At the end of your username type in the pipe character "|" (under the backspace key, using shift). Do not add any spaces. Enter your desired seed after the pipe character and login to spawn at the seed location.


/twin - **How To Twin (Play With Friends)**

Twinning is the broad term used for spawning with up to 3 friends at the same location at the same time.  It is the most convenient way to play with friends.

To twin, press the **[FRIENDS]** button.  Then, you will see a twin code at the top of the screen.  Randomly generated twin codes are 3 random words.  You can put whatever you want as your twin code, as long as it matches what your friend(s) puts in.  After you have your twin code written, press the button at the bottom for how many players will be using the code.
Twins = 2 people
Triplets = 3 people
Quadruplets = 4 people
After you have pressed the button, hit **[BE BORN]**  The screen will say "Waiting to be born as twins/triplets/quadruplets." until the last person hits **[BE BORN]**.

If any of the group has a seed in either seed box, the twins will spawn as eves there.  Sadly the eves aren't related, but will all have the same model.  You can all choose different last names.  If multiple people have seeds, the last person with one to hit **[BE BORN]** will decide where the game places you.  If you do not want to spawn as eves, make sure that everyone in the group has removed their seeds.  Then, you will spawn as babies to the same mother at the same time.  You will be identical twins and all have the same model.


New guides:

/minitech - **Minitech**

Minitech, like it's name might imply, is a mini version of the official 2HOL crafting guide, [Twotech](https://twotech.twohoursonelife.com/).  Minitech is a small menu that sits above your temperature meter at the bottom right corner of your screen as you play.  To activate it, simply click on the black rectangle that says '[+] crafting guide'.  Minitech will also automatically activate when you interact with your first item in a new life.  To close, simply click the '[-]' (minus sign) in the top right.  You can also use the key "v" to open or close minitech.

Minitech is a very helpful tool for finding out how to craft items, and what to do with current items.  If you type '/item name' (/dynamite, /cookie, /reed backpack, etc), then maximize minitech, you will be shown recipes for said object.  You can toggle between *how to make*, and *how to use*, by clicking those buttons at the top.  To clear minitech, simply type a slash "/".  Minitech will also show you recipes for the last item that you have interacted with.  Only 1 step of any recipe is shown on minitech at once.  However, you are able to go down the steps by clicking on the pictures of the items.  This allows you to go backward or forward through a recipe to get to your ideal point, as well as head back to your original search, if needed.


/craving - **Cravings** (2HOL guide)

You will get your first craving at age 10.  Your first craving is what food your mother was craving at the time you were born.  Eves spawn with a simple craving.

Cravings only change after you have satisfied your previous one.  Getting ones that you can fulfill with what you have access to currently in town is down to luck (you may crave roasted fish but not have fishing equipment), and what the rest of your family has previously eaten (if your uncle eats a steak and onion pie and it’s the most advanced thing that your someone in your family has eaten, your family is moved to the “moderate”difficulty for foods).  You share the same craving list with your entire family, but some branches may be more progressed than others.


/yum - **Yum Chaining** (2HOL guide) 

Yum is an important mechanic to learn in 2HOL.  Yum chaining allows you to go longer without eating. 

When holding a food, look in the bottom left corner of your screen.  It will say either ‘yum’ or ‘meh’ above your Food Meter (this is also how you know something is edible).  Every food item is yum once per life.  If you have not eaten the food yet in your current life, it will say ‘yum’.  If you have, it will say ‘meh’ for the remainder of your life. 

The more yum foods you eat in your life, the more benefits you get for each food.  This is what’s known as a yum chain, because you are adding the effects of each new yum item to the last.  The amount of unique foods that you have eaten is shown by a “#x” above your Food Meter.  If you’ve eaten an apple, an orange, and some roasted rabbit, this number will be “3x”.  The multiple -1 is equal to how many bonus food boxes that you get when you eat your next yum food.  In that example’s case, say you eat a lemon; the multiple will now be “4x” and you’ll get 3 extra food boxes.  Now imagine this as you’ve slowly gained a yum chain throughout your life.  You could have a chain of 20, and your next food would give you 20 extra boxes. 

Don’t worry about wasting food when yumming.  There is food overflow!  Sometimes you will notice a “+#” above your Food Meter.  This number represents how many food squares you actually have, besides your visible Food Meter.  Yum bonus will always go to this overflow. 

The idea of yum chaining is to make players always strive to eat new foods, over just relying on a ‘meta’, or easy foods. 
(Credit to liger for revamping this guide!)

**Comment by connorhsm** [comment]
Done in 1.1.4, thank you.
